- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ nginx_docker_path }}"
    owner: "{{ nginx_docker_file_owner }}"
    group: "{{ nginx_docker_file_group }}"
    state: directory
    mode: 0755

- name: Create nginx proxy config
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ nginx_docker_path }}/default.conf"
    owner: "{{ nginx_docker_file_owner }}"
    group: "{{ nginx_docker_file_group }}"
    mode: 0644
  notify: restart nginx

- name: Create nginx docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nginx_docker_path }}/docker-compose.yml"
    owner: "{{ nginx_docker_file_owner }}"
    group: "{{ nginx_docker_file_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart nginx

- name: Validate docker compose file
  ansible.builtin.command: docker compose config --quiet
  args:
    chdir: "{{ nginx_docker_path }}"
  changed_when: false

- name: Startup container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ nginx_docker_path }}"
  register: nginx_container_startup
  changed_when: "'Started' in nginx_container_startup.stdout"
