# pi-hole variables
pihole_docker_environment:
  - "TZ=Europe/Berlin"
  - "WEBPASSWORD=<some_password>"

# [dockerhub](https://hub.docker.com/r/pihole/pihole)
pihole_docker_image: "pihole/pihole:latest"

# pi-hole exporter variables
pihole_exporter_docker_environment:
  - "PIHOLE_HOSTNAME=192.168.1.2"
  - "PIHOLE_PASSWORD=<some_password>"

# [dockerhub](https://hub.docker.com/r/ekofr/pihole-exporter)
pihole_exporter_docker_image: "ekofr/pihole-exporter:latest"

# pi-hole local dns records
pihole_docker_dns_records:
  - name: pihole.local
    ip: 192.168.1.2
    cname: dns.local
