- hosts: all
  pre_tasks:
  - name: Include Variables
    ansible.builtin.include_vars: config.yml

  roles:
  - role: pihole

  post_tasks:
  - name: Ensure Pi-hole http is reachable (port 80)
    ansible.builtin.wait_for:
      port: 80

  - name: Ensure Pi-hole dns is reachable (port 53)
    ansible.builtin.wait_for:
      port: 53
